name: avatar_better
description: "This is a complete avatar package that you can use for your profile and avatar."
version: 1.0.2
homepage: https://github.com/SwanFlutter/avatar_better.git
uses-material-design: true

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  zoom_hover_pinch_image: ^1.1.0
  flutter_saver: ^0.0.6
  path_provider: ^2.1.5
  picker_image_cropper: ^0.0.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


